serect_key: fb0bc76a-dbb1-4944-bcf7-aaef0d9d6e95
verify_config: false
database_connection_info:
  db_type: "postgres"
  db_username: "postgres"
  db_password: "example"
  db_name: "fortress"
  db_ssl_mode_option: "disable"
  db_hostname: "localhost"
  db_port: "5432"
  db_environment: "development"
  db_schema_name: "public"
  user_with_acl:
    username: agent_db_manager
    password: this_is_password
model_list:
  - table_name: "users"
    display_name: "users"
    name_display_column: "name"
    acl: "crud"
    auto_migration: true
    hooks:
      enable: true
      before_create:
        enable: true
        content: "println(\"it run on before create config\")"
      after_create:
        enable: false
        content: "println(\"it run on after create config\")"
      before_update:
        enable: false
        content: "println(\"it run on before update config\")"
      after_update:
        enable: false
        content: "println(\"it run on after update config\")"
    columns:
      - name: id
        type: int
        is_primary: true
      - name: name
        type: string
        is_nullable: true
      - name: title
        type: string
        is_nullable: true
      - name: description
        type: string
        is_nullable: true
      - name: age
        type: int
        is_nullable: true
  - table_name: "books"
    display_name: "users"
    name_display_column: "name"
    acl: "cru"
    auto_migration: true
    columns:
      - name: id
        type: int
        is_primary: true
      - name: created_at
        type: timestamp
        is_nullable: true
      - name: updated_at
        type: timestamp
        is_nullable: true
      - name: deleted_at
        type: timestamp
        is_nullable: true
      - name: name
        type: string
        is_nullable: false
      - name: title
        type: string
        is_nullable: true
      - name: description
        type: string
        is_nullable: true
      - name: age
        type: int
        is_nullable: true
